version: '3'
services:
  pg:
    image: postgres
    container_name: anymind-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: pos_app
    ports:
      - "2345:5432"
    networks:
      - anymind-net
  app:
    build: .
    ports:
      - "9090:9090"
      - "8080:8080"
    container_name: anymind-pos-api
    depends_on:
      - pg

    networks:
      - anymind-net

networks:
  anymind-net: